id: P007988
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:35.490697
source_metadata:
  id: bdr:W1KG5775
  title: མདའ་དང་འཕང། མཁར་རྨེའུ་བསམ་གཏན་གྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    6cca4305759c4151bb3a137cdf8406de:
      image_group_id: I1KG5784
      title: Volume 1 of mda' dang 'phang/ mkhar rme'u bsam gtan gyi gsung rtsom phyogs
        bsgrigs
      volume_number: 1
      total_pages: 510
      base_file: v001.txt
    1877c5d9fb9f4675bdae29f42104388a:
      image_group_id: I1KG5785
      title: Volume 2 of mda' dang 'phang/ mkhar rme'u bsam gtan gyi gsung rtsom phyogs
        bsgrigs
      volume_number: 2
      total_pages: 540
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
