id: P007988
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5775
  title: མདའ་དང་འཕང། མཁར་རྨེའུ་བསམ་གཏན་གྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    750883a725034aa2bfe055435211ec81:
      image_group_id: I1KG5784
      title: ''
      volume_number: 1
      total_pages: 510
    d33b2f935dfb4ed19665825c553b2425:
      image_group_id: I1KG5785
      title: ''
      volume_number: 2
      total_pages: 540
ebook_metadata:
  title: མདའ་དང་འཕང། མཁར་རྨེའུ་བསམ་གཏན་གྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007988
  cover: cover.jpg
  layers:
  - pagination
