id: I107B2599
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:22:36+00:00'
last_modified: '2022-06-09T08:21:27.056250+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5775
  title: མདའ་དང་འཕང། མཁར་རྨེའུ་བསམ་གཏན་གྱི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C2E3:
      image_group_id: I1KG5784
      title: Volume 1 of mda' dang 'phang/ mkhar rme'u bsam gtan gyi gsung rtsom phyogs
        bsgrigs
      total_pages: 510
      order: 1
      base_file: C2E3.txt
    744C:
      image_group_id: I1KG5785
      title: Volume 2 of mda' dang 'phang/ mkhar rme'u bsam gtan gyi gsung rtsom phyogs
        bsgrigs
      total_pages: 540
      order: 2
      base_file: 744C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
